import frappe


# After Insert
def after_insert(doc, event):

    if doc.doctype != "Sales Order":
        return

    # -----------------------------
    # 1. Append Project ID to Sales Order name
    # -----------------------------
    project = doc.project

    if not project:
        return  # should not happen, because mandatory

    # Fetch project document
    project = frappe.get_doc("Project", doc.project)

    # project.id or project.name ?
    # Using project.name because this is the actual ID generated by naming series.
    project_id = project.name

    # Already renamed?
    if project_id in doc.name:
        return

    # new name format → SO-####-<ProjectID>
    # project_id = project.split(":")[0] if "-" in project else project
    new_name = f"{doc.name}: {project_id}"

    # if name already matches pattern, skip
    if new_name == doc.name:
        return

    # rename Sales Order safely
    frappe.rename_doc(
        doctype="Sales Order",
        old=doc.name,
        new=new_name,
        force=True,
        merge=False
    )

    # update in-memory instance
    doc.name = new_name

    # -----------------------------
    # 2. Link Sales Order back to Project
    # -----------------------------
    project = frappe.get_doc("Project", project_id)

    updated = False

    # Set Sales Order reference on Project (optional field — use custom field or default field)
    # If you already have a field: 'sales_order'
    if hasattr(project, "sales_order"):
        if not project.sales_order:
            project.sales_order = doc.name
            updated = True
    else:
        # If field doesn't exist, add a comment instead so link still exists
        if not frappe.db.exists("Communication", {"reference_doctype": "Project", "reference_name": project_id, "subject": doc.name}):
            project.add_comment("Info", f"Linked Sales Order: {doc.name}")

    # -----------------------------
    # 3. Link Customer to Project (if not already linked)
    # -----------------------------
    # Project usually has a field called 'customer' (ERPNext Standard)
    if hasattr(project, "customer"):
        if not project.customer:
            project.customer = doc.customer
            updated = True

    # -----------------------------
    # 4. Save only if fields were updated
    # -----------------------------
    if updated:
        project.save(ignore_permissions=True)


# # Add boolean field
# def create_custom_auto_generate_project_field():
#     """Add 'Auto Generate Project' checkbox to Sales Order"""
#     if not frappe.db.exists("Custom Field", {"dt": "Sales Order", "fieldname": "custom_auto_generate_project"}):
#         frappe.get_doc({
#             "doctype": "Custom Field",
#             "dt": "Sales Order",
#             "fieldname": "custom_auto_generate_project",
#             "label": "Auto Generate Project",
#             "fieldtype": "Check",
#             "insert_after": "customer",  # adjust position as needed
#             "default": 1,
#             "module": "Selling",
#         }).insert(ignore_permissions=True)
#         frappe.clear_cache(doctype="Sales Order")
#       })

#         # Bypass ALL validate hooks (safe for auto-creation)
#         # project.flags.ignore_validate = True
#         project.insert(ignore_permissions=True)

#         # Rename project to be more descriptive
#         new_name = f"{project.name} : {doc.customer_name} : {doc.name}"
#         project.db_set("project_name", new_name)

#         # Link back to Sales Order
#         doc.db_set("project", project.name)

#         frappe.msgprint(
#             f"Project <b>{project.name}</b> created for Sales Order <b>{doc.name}</b>", indicator="green")



# # on Sales Order Submit create a peoject
# def on_submit(doc, method):
#     # If Auto generation flag is set
#     if doc.custom_auto_generate_project and not doc.project:
#         project = frappe.get_doc({
#             "doctype": "Project",
#             "project_name": f"Project for {doc.name} - {doc.customer_name}",
#             "customer": doc.customer,
#             "sales_order": doc.name,
#             "expected_start_date": doc.transaction_date,
#             "expected_end_date": doc.delivery_date,
#             "status": "Open"
#         })

#         # Bypass ALL validate hooks (safe for auto-creation)
#         # project.flags.ignore_validate = True
#         project.insert(ignore_permissions=True)

#         # Rename project to be more descriptive
#         new_name = f"{project.name} : {doc.customer_name} : {doc.name}"
#         project.db_set("project_name", new_name)

#         # Link back to Sales Order
#         doc.db_set("project", project.name)

#         frappe.msgprint(
#             f"Project <b>{project.name}</b> created for Sales Order <b>{doc.name}</b>", indicator="green")
  